### ISSUE TITLE
Claiming namespace [marus25]

### ISSUE THREAD

**Issue by haneefdm** [EclipseFdn/open-vsx.org#1673]
I am the sole maintainer of this extension for VSCode. I published all the releases in the last couple of years. The version here is way out of date. I don't own `marus25` org. on the VSCode side as the person left me as a caretaker and I have permission to publish, manage issues/PRs, etc.

There are a bunch of other related extensions that all work together under the `mcu-debug` namespace. I published a few recently and there will be more coming -- if I can claim `marus25`. The cortex-debug extension relies on the functionality of these other extensions

Any help/advice is appreciated

**Comment by haneefdm** [comment]
CC: @marus

Marcel is the owner of the repo and the namespace/org `marus25` in the VSCode marketplace.

**Comment by kineticsquid** [comment]
@haneefdm Just want to make sure I understand. Are you saying that @marus is the owner of this namespace in the VS Code Registry and that they are OK with you owning the namespace in the Open VSX Registry?

**Comment by Marus** [comment]
Yes - at this point @haneefdm maintains the `cortex-debug` extensions for VS Code; so would be good to get the `marus25` namespace/org in the OpenVSX registry for consistency so that he can also publish the extension to the OpenVSX registry in a consistent namespace. Either owned by Haneef directly - or owned by myself with Haneef having the appropriate permissions to publish.

**Comment by haneefdm** [comment]
Thanks, @Marus

**Comment by kineticsquid** [comment]
Indeed, thanks @Marus. @haneefdm, it's yours! Thanks for your contributions.
