### ISSUE TITLE
`[extension]` already published, but currently isn't active and therefore not visible

### ISSUE THREAD

**Issue by filiptronicek** [EclipseFdn/open-vsx.org#2062]
For many extensions, something goes wrong during the publishing making the new versions not "active" on the registry.

This happens for many extensions and is really inconvenient, because there is no apparent action to be taken on the side of the extension author. The occurrence of this issue seems random and I don't see a pattern with what goes and what doesn't.

From the logs:
```
❌ Extension ms-toolsai.jupyter 2023.8.100 is already published, but currently isn't active and therefore not visible.
```

Possibly related to #1444

**Comment by filiptronicek** [comment]
Notably, this is happening for the following extensions:
- `ms-toolsai.jupyter` (1.1M downloads)
- `golang.Go`(307K downloads)

@kineticsquid I think we should mark this as a high-priority issue, because it's disrupting the use of the registry 🙏

**Comment by filiptronicek** [comment]
I just tried publishing a smaller extension and the same issue occured. It looks pretty widespread.

**Comment by kineticsquid** [comment]
@filiptronicek Agree with the priority and agree that something funny is going on. Here's another data point: https://github.com/EclipseFdn/open-vsx.org/issues/2050. In this case, it looks like the extension got into a bad state with a publication that was not activated. Then, no matter what was published, it was not activated. I tried and failed. I was able to publish to the same code to my namespace with no problem. When I removed the deactivated versions, I was able to publish.

**Comment by filiptronicek** [comment]
Because of this issue, our biggest extension on the public instance of the registry, `ms-python.python` with close to 2 million downloads is outdated by two release versions. 

I am not sure how exactly we can proceed here considering the scale. @kineticsquid could you for these cases try to unpublish the extensions listed above so that I can try re-publishing them? It's no long-term solution, but I'm curious to see how exactly it will come back

**Comment by kineticsquid** [comment]
@filiptronicek I tried a few experiments last night. The extensions `golang.Go` and `bradlc.vscode-tailwindcss` provided `.vsix` files for the releases, the other do not. I downloaded the latest version we show as active and all the releases after those. I then attempted to publish these extension versions to our staging environment. The publishing was successful including the versions that are showing as deactivated in production. 

I then added myself as a contributor to these two name spaces in production and attempted to publish the same `.vsix` files. That worked. You can see the more recent versions for `Go` and `vscode-tailwindcss`.

I removed `ms-toolsai.jupyter 2023.8.100` and `ms-python.python 2023.14.0`, these were the releases that were not activated. Can you try to re-publish these now. One thing I noted, the repo link for the Jupyter extension only gad releases up to 2022. 

If these works, I'd like to go back and remove the other versions I published and have you re-publish those.

**Comment by filiptronicek** [comment]
Thanks a bunch for your effort here, @kineticsquid 🙏. I'll take a look at Python and Jupyter now - Jupyter indeed has stoppped publishing GitHub Releases, so they only release to the Microsoft Marketplace now. 

I'll get back to you and we'll see about republishing the extensions you fixed.

**Comment by filiptronicek** [comment]
@kineticsquid Python and Jupyter published ✅

**Comment by kineticsquid** [comment]
Woo Hoo!

**Comment by DanTup** [comment]
I published v3.72.0 of the Dart extension earlier today, and then 3.72.1 with a fix around 30 mins ago. The initial release showed up, but I'm seeing this issue after publishing the fix. I'm not sure whether it just takes a while to go through or if it's broken.

The fix is quite important so if it doesn't show up in the next 2-30 mins I'm just going to bump the version number and try again, but I thought it was worth recording here in case you can gain any insight from logs/whatever.

**Comment by kineticsquid** [comment]
@amvanbaren Might be able to add more here. The file processing is done asynchronously. As a consequence of this, an extension tile will show deactivated until the file processing is complete (and there are no errors). 

@zFernand0 Any idea how long after publishing it took your extension to show up as active? 

@DanTup Similar question, how long after your extension showed as active it take for `ovsx --metadata` to return the info?

**Comment by DanTup** [comment]
@kineticsquid it showed up in metadata very shortly after it showed up on the website (right after I posted above). So it was around 1hr for the extension to show up both on the website + metadata, there was just a very slight delay between them (which I suspect was just some caching).

**Comment by filiptronicek** [comment]
@kineticsquid could you please look into removing the latest of https://open-vsx.org/extension/vscjava/vscode-java-test? It should be `0.40.0` in the database and server, but probably not enabled again, since we cannot publish to the version, although this time with no error message – just a successful message from the CLI, although publishing the same version multiple times.

The latest downloadable version, `0.39.1` has shown to [be broken](https://github.com/open-vsx/publish-extensions/issues/715), therefore the need to update to `0.40.0`.

**Comment by kineticsquid** [comment]
unpublish both `0.39.1` and `0.40.0`?

**Comment by kineticsquid** [comment]
Removed `0.40.0`.

**Comment by kineticsquid** [comment]
@filiptronicek @amvanbaren Do we need to keep this one open?

**Comment by filiptronicek** [comment]
@kineticsquid let's close and re-open if needed 🙏

**Comment by hoangphamEclipse** [comment]
I investigated this issue on my end and I have some interesting findings that I would like to share. While debugging locally, I found out that this is a concurrency issue. When a new extension is published, the web ui will send a request to the server to publish the extension [1], then immediately send another request to re-fetch the list of extensions published by the user [2]. The server will run these 2 requests in parallel.

The problem occurs because we are trying to write to the database while performing a `GET` request. The diagram below shows how [1] and [2] affect the `active` status of an extension as they are executed when the error happens.

![image](https://github.com/EclipseFdn/open-vsx.org/assets/92533264/21693ec6-b3db-49b0-9dad-9082976649aa)

The problem is caused exactly by this line: https://github.com/eclipse/openvsx/blob/84d01402f007233c8a1e5b28587e4f4784c7d3fd/server/src/main/java/org/eclipse/openvsx/util/VersionService.java#L38

`entityManager.merge(extension)` will try to persist the `extension` parameter to the database. If `extension` is stale - that is if it is retrieved before its status is updated by [2] - then the `entityManager` will overwrite the changes done by [2] with the stale version, ultimately making the extension inactive. I think the intention of calling `merge(extension)` is to obtain a JPA managed `extension` thus enabling the code to fetch its `extension versions` lazily; however, the side effect is this bug.

**Comment by kineticsquid** [comment]
@DanTup `3.80.0` is toast.

**Comment by DanTup** [comment]
@kineticsquid thanks! I re-published that one and it's showing up now :)

**Comment by sjsepan3** [comment]
Just had this happen.
[https://github.com/eclipse/openvsx/issues/783#issuecomment-2347240693](https://github.com/eclipse/openvsx/issues/783#issuecomment-2347240693)

**Comment by kineticsquid** [comment]
@sjsepan3 I can see you have other extensions that seem to be publishing successfully. Sometimes, though not always, extensions fail to activate because of an error in the package contents (admittedly we don't do a good job of reporting on this). I'd investigate but the repos above appear to be private.

**Comment by sjsepan3** [comment]
> @sjsepan3 I can see you have other extensions that seem to be publishing successfully. Sometimes, though not always, extensions fail to activate because of an error in the package contents (admittedly we don't do a good job of reporting on this). I'd investigate but the repos above appear to be private.

The GitLab links were a long-standing error that was among the things I was updating with this latest round of publishing.
An example of a corrected one is:

[https://gitlab.com/sjsepan/sjsepan-nevadaish](https://gitlab.com/sjsepan/sjsepan-nevadaish)

Steve

**Comment by kineticsquid** [comment]
@sjsepan3 I cloned your repo and attempted to build the extension. I get this error message:
```
 ERROR  The specified icon 'extension/./images/icon.png' wasn't found in the extension.
```

I then changed this line in your `package.json` file:
```
	"icon": "./images/icon.png",
```
to:
```
	"icon": "images/icon.png",
```
Packaged it again and published and it activated.

**Comment by sjsepan3** [comment]
> @sjsepan3 I cloned your repo and attempted to build the extension. I get this error message:
> 
> ```
>  ERROR  The specified icon 'extension/./images/icon.png' wasn't found in the extension.
> ```
> 
> I then changed this line in your `package.json` file:
> 
> ```
> 	"icon": "./images/icon.png",
> ```
> 
> to:
> 
> ```
> 	"icon": "images/icon.png",
> ```
> 
> Packaged it again and published and it activated.
@kineticsquid 
Thank You for tracking that down.
Now that brings up some questions/observations...

-how does one determine this from the publish process
-the path ought to evaluate to the same thing, but I can simplify it
-however, I wonder if I used that format because the simpler form was not working
-now that i think about it, although I am used to working on Linux, I wonder if  forward-slash would work on Windows. I have not had trouble installing the extensions in WIndows
-with that change, I'll have to re-upload to the MS Mkt and see if it squawks
-since that one has uploaded successfully in the past, what caused it to fail this time, as that is not something I changed this time, and these had been out there for months.  (I can see that my non-theme extensions do not have './' in that setting, but probably all of the themes were out there at one time with that value.)
-finally, how does one determine these kind of errors during the publish process?

**Comment by sjsepan3** [comment]
@kineticsquid 
I just made that change to a local copy v0.0.4 (not pushed to GitLab yet), and it publishes, but is not active; I see v0.0.2 active.

**Comment by kineticsquid** [comment]
@sjsepan3 Using my admin super powers I removed v `0.0.4`. I then added myself to your namespace as a contributor and published the `0.0.4` I packaged.  It activated. I then removed myself from your namespace. I'm thinking this must be something with your packaging process. I just used `vsce package` from the root directory. It was in packaging this way that I say the error I listed above. 

Are you saying that some of these extension versions that were active because deactivated? Or that you published new versions, without changing anything and the newer versions didn't activate?

**Comment by sjsepan3** [comment]
> @sjsepan3 Using my admin super powers I removed v `0.0.4`. I then added myself to your namespace as a contributor and published the `0.0.4` I packaged. It activated. I then removed myself from your namespace. I'm thinking this must be something with your packaging process. I just used `vsce package` from the root directory. It was in packaging this way that I say the error I listed above.

I will have to re-investigate vsce package`, although the "root" where I run it will likely be the pkg folder, because that is the content that goes into a .vsix. 

> Are you saying that some of these extension versions that were active because deactivated? Or that you published new versions, without changing anything and the newer versions didn't activate?

The latter, except I did change the .json file in several and the .vsixmanifest file in all of them.

**Comment by sjsepan3** [comment]
@kineticsquid 
I was able to get `vsce ls --tree` and `vsce package` to run, only when inside the extension folder (the level below the pkg folder where the manifest resides) and the .vsix generated both publishes and activates.

You can consider this closed. 

I have opened up the generated .vsix (it is jsut a .zip with a folder structure and content like my extension folder) and I'm looking for differences -- because I want to know why my bash-generated packages worked for so long and suddenly stopped working here. So far the only differences (according to Meld) are in what goes into the content types and the manifest. The former omitted the xml mime time I had (`<Default Extension=".xml" ContentType="text/xml"/>`), and the latter encoded `&apos;`, omitted my PreviewImage key, and added some additional keys (Microsoft.VisualStudio.Code.EnabledApiProposals,
Microsoft.VisualStudio.Services.Links.Getstarted,
Microsoft.VisualStudio.Services.Links.Repository,
Microsoft.VisualStudio.Services.Links.Learn).

**Comment by sjsepan3** [comment]
@kineticsquid 
Some additional tests...and I should note that running `vsce package` does not show any errors with the content:

- I made changes to content types and manifest based on what vsce generated, and since that content worked with vsce packaging, I packaged that content with bash script zip, but although it publishes, it does not activate
- I took a zip file generated by vsce, scooped out the contents, put in the same content  that I had zipped myself, but although it publishes, it does not activate
- I took the content out of a vsce-generated pkg and zipped that myself, but although it publishes, it does not activate
- 
So far it is looking like it is not the content, but the archive (`zip -r`).

**Comment by amvanbaren** [comment]
Hi @sjsepan3,
Yes, it's the archive. It's being flagged as potentially malicious.
Here's an excerpt from the logs:
```
2024-09-19T12:40:55.070Z  WARN [openvsx-server,,] 1 --- [openvsx-server] [task-35] o.e.o.p.PublishExtensionVersionHandler   : Extension version is potentially malicious: sjsepan.sjsepan-pippish 0.1.7
2024-09-19T12:32:44.111Z  WARN [openvsx-server,,] 1 --- [openvsx-server] [task-34] o.e.o.p.PublishExtensionVersionHandler   : Extension version is potentially malicious: sjsepan.sjsepan-pippish 0.1.6
2024-09-19T12:13:04.235Z  WARN [openvsx-server,,] 1 --- [openvsx-server] [task-72] o.e.o.p.PublishExtensionVersionHandler   : Extension version is potentially malicious: sjsepan.sjsepan-pippish 0.1.5
2024-09-19T12:03:19.040Z  WARN [openvsx-server,,] 1 --- [openvsx-server] [task-33] o.e.o.p.PublishExtensionVersionHandler   : Extension version is potentially malicious: sjsepan.sjsepan-pippish 0.1.4
2024-09-19T01:49:01.131Z  WARN [openvsx-server,,] 1 --- [openvsx-server] [task-2]  o.e.o.p.PublishExtensionVersionHandler   : Extension version is potentially malicious: sjsepan.sjsepan-pippish 0.1.2
```

Please use `ovsx` or `vsce` to package your extensions.

**Comment by sjsepan3** [comment]
> Hi @sjsepan3, Yes, it's the archive. It's being flagged as potentially malicious. Here's an excerpt from the logs:
> 
> ```
> 2024-09-19T12:40:55.070Z  WARN [openvsx-server,,] 1 --- [openvsx-server] [task-35] o.e.o.p.PublishExtensionVersionHandler   : Extension version is potentially malicious: sjsepan.sjsepan-pippish 0.1.7
> 2024-09-19T12:32:44.111Z  WARN [openvsx-server,,] 1 --- [openvsx-server] [task-34] o.e.o.p.PublishExtensionVersionHandler   : Extension version is potentially malicious: sjsepan.sjsepan-pippish 0.1.6
> 2024-09-19T12:13:04.235Z  WARN [openvsx-server,,] 1 --- [openvsx-server] [task-72] o.e.o.p.PublishExtensionVersionHandler   : Extension version is potentially malicious: sjsepan.sjsepan-pippish 0.1.5
> 2024-09-19T12:03:19.040Z  WARN [openvsx-server,,] 1 --- [openvsx-server] [task-33] o.e.o.p.PublishExtensionVersionHandler   : Extension version is potentially malicious: sjsepan.sjsepan-pippish 0.1.4
> 2024-09-19T01:49:01.131Z  WARN [openvsx-server,,] 1 --- [openvsx-server] [task-2]  o.e.o.p.PublishExtensionVersionHandler   : Extension version is potentially malicious: sjsepan.sjsepan-pippish 0.1.2
> ```
> 
> Please use `ovsx` or `vsce` to package your extensions.

Well that's a detail that we didn't see  before. I don't like magic -- its just a zip file. The layout I used inside is the same, and the content is the same. Is there some sort of hidden signing going on?

**Comment by sjsepan3** [comment]
> You can do some interesting things with a ZIP archive's extra field: https://gitlab.eclipse.org/security/vulnerability-reports/-/issues/213

I see, Thank You. Good enough reason to alter my workflow slightly. VSCE it is. 

> Please use **ovsx** or vsce to package your extensions.

BTW, I don't see a _package_ option in the OVSX tool help. I've started using vsce, but what am I missing in the ovsx tool?

**Comment by amvanbaren** [comment]
> I've started using vsce, but how do I do that in the ovsx tool?

`ovsx` uses `vsce` for packaging.
If you only publish to open-vsx.org you can run `ovsx publish --packagePath <path>`. It packages the extension and then publishes it.

If you also publish to the MS marketplace, then just package (and publish) the extension using `vsce` and use `ovsx publish <packagePath>` to publish to open-vsx.org.

**Comment by sjsepan3** [comment]
> > I've started using vsce, but how do I do that in the ovsx tool?
> 
> `ovsx` uses `vsce` for packaging. If you only publish to open-vsx.org you can run `ovsx publish --packagePath <path>`. It packages the extension and then publishes it.
> 
> If you also publish to the MS marketplace, then just package (and publish) the extension using `vsce` and use `ovsx publish <packagePath>` to publish to open-vsx.org.

OK, nothing for me to do differently with that, then. Thank You @amvanbaren !

**Comment by kineticsquid** [comment]
@sjsepan3 No worries, glad we got to the bottom of this.

**Comment by rgrunber** [comment]
I think vscode-java has been hit by this as well :

We successfully published 1.40.0 at the end of February : 
https://github.com/redhat-developer/vscode-java/actions/runs/13558938209/job/37918995790

```bash
🚀  Published redhat.java v1.40.0@darwin-arm64
🚀  Published redhat.java v1.40.0@darwin-x64
🚀  Published redhat.java v1.40.0@linux-arm64
🚀  Published redhat.java v1.40.0@linux-x64
🚀  Published redhat.java v1.40.0@win32-x64
🚀  Published redhat.java v1.40.0
```

However https://open-vsx.org/api/redhat/java/1.40.0 is empty (compared to https://open-vsx.org/api/redhat/java/1.39.0). Given that it appeared like OpenVSX Registry simply didn't publish, I decided to do it manually and got this :

```bash
❌  Extension redhat.java 1.40.0 (darwin-arm64) is already published, but currently isn't active and therefore not visible.
See the documentation for more information:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
```

If someone is able to unpublish those 6 extensions (1.40.0) mentioned above that would be great, so that I can try to republish.

**Comment by tfroment** [comment]
> redhat/java/1.40.0

Hi @rgrunber  I just removed version 1.40.0, tell me if it solve the issue

**Comment by rgrunber** [comment]
That seems to have fixed it, https://open-vsx.org/api/redhat/java/1.40.0. Thank-you!

**Comment by KarimGhallab** [comment]
Hello, I think I ran into the same issue.

I'm trying to publish my extension, but I encountered an error that made the package inactive:
`Extension Mobioos.mobioos-forge 2.2.6 is already published, but currently isn't active and therefore not visible.`

I didn’t find any way to delete the package myself in order to perform a clean upload.
Thank you in advance for any help you can provide!

**Comment by AmaranthineCodices** [comment]
We're seeing this on [`modular-mojotools.vscode-mojo 26.0.0`](https://open-vsx.org/extension/modular-mojotools/vscode-mojo), which hasn't been published. Trying to publish a patch release (26.0.1) failed as well.

**Comment by netomi** [comment]
this is most likely related to the check for potentially malicious vsix packages.

If extra fields are detected the activation of an extension is disabled but this only happened after the extension was published. This has been changed to a pre-publish check in https://github.com/eclipse-openvsx/openvsx/pull/1721

Your publication will fail right away with proper feedback and you can re-upload after fixing these issues.
