### ISSUE TITLE
Claiming namespace kineticSnippet

### ISSUE THREAD

**Issue by kineticSnippet** [EclipseFdn/open-vsx.org#2082]
I published this extension: https://open-vsx.org/extension/kineticSnippet/add-items
This is the repo I own with the extension: https://github.com/kineticSnippet/AddItems

**Comment by kineticsquid** [comment]
I like it!

**Comment by theFish2171** [comment]
Hi, I'm so sorry, I'm trying to get in touch with Eclipse foundation because I've changed my username, and can't edit it on the eclipse website, I've already sent emails requesting to change my username to match my GitHub. I'm so sorry to reach out by this way, it was my first open source project, or project in general, and I didn't really know how to proceed. 

I haven't been able to update it, and since I'm using VSCodium now, I would really love to use my (up-to-date) extension, I would love any support or guidance on your end!

Best, fish

![image](https://github.com/user-attachments/assets/5931f90c-5c5f-42e8-a93a-e646fa710955)
