### ISSUE TITLE
Request Entity Too Large when publishing extension

### ISSUE THREAD

**Issue by amvanbaren** [EclipseFdn/open-vsx.org#2300]
@tivervac asked in https://github.com/eclipse/openvsx/issues/845: 
I'm trying to publish my extension via the web interface (PUBLISH EXTENSION [here](https://open-vsx.org/user-settings/extensions)). 
This worked fine in the past, but now I get the error message shown below. The .vsix is 272.74MB large.

I'm moving the question to this repo, because the openvsx server upload limit is 512 MB.
I think it is a proxy server that rejects the upload.

**Comment by kineticsquid** [comment]
@amvanbaren Is this in Eclipse infra or elsewhere?

**Comment by amvanbaren** [comment]
@kineticsquid It looks like it is in Eclipse infra.

**Comment by kineticsquid** [comment]
Yeah, I was able to reproduce this on both production and staging.

**Comment by agafgfafa** [comment]
> I'm moving the question to this repo, because the openvsx server upload limit is 512 MB.

How/where is that limit set?

**Comment by tivervac** [comment]
Good progress so far, @kineticsquid how can we continue on this ticket?

**Comment by agafgfafa** [comment]
A patch is pending on the Eclipse infra. Stay tuned.

**Comment by agafgfafa** [comment]
Just out of idle curiosity, what is contained inside a 272MB payload?

**Comment by agafgfafa** [comment]
Arguably, that's not an extension, but a complete operating system, no?

**Comment by agafgfafa** [comment]
While most extensions seem to be a few KB in size, to several MB in some cases, I'd like to get a sense that 250 MB is a normal size for an extension before increasing limits. Is there any way your extension could be trimmed, or fetch third-arty dependencies from their source locations rather than packaging them up?

**Comment by tivervac** [comment]
Arguably, sure.

I would say this is quite typical in our business (IDEs). IDEs by themselves are usually quite hefty, and that's not just because of the UI they ship. The extension could be trimmed, but not in a significant way you're looking for. We used to offer fetching from third parties, but this was not the experience our clients sought. It's more bug-prone, it disrupts the initial flow (install and then install again?), you're required to have a stable connection for longer (our clients are usually disconnected from the net), etc. Providing everything that'll ever be needed in the initial package makes the experience much more streamlined.

**Comment by tivervac** [comment]
Note that to be completely compatible with the VS Code, at least this file size should be accepted. I'm not sure what their limit is, but our extension is accepted without issues

**Comment by kineticsquid** [comment]
@tivervac Confirming that, previously, you were able to publish your extension of this size on open-vsx.org? What is your extension?

**Comment by tivervac** [comment]
I had a look, and the version we have uploaded as of now is 212M large. The next release (that we can't upload) seems to have passed the magic 256MB, as it's now 273M. That might seem like a significant increase, but no worries, this was exclusive and won't happen every release. The plugin in question is [Sigasi](https://open-vsx.org/extension/Sigasi/sigasi-vscode)

**Comment by kineticsquid** [comment]
@tivervac Thanks, I can see your previously published versions at open-vsx.org are all less than 256M and that you've successfully published your 273M version, `5.4.2`, to the Visual Studio Marketplace. @agafgfafa @amvanbaren Ideally, we'd be consistent with VS Marketplace with this size limitation. That said, this is the first time we've encountered a conflict with the restriction. How much of a lift would this be to change?

**Comment by amvanbaren** [comment]
The OpenVSX server supports up to 512MB. I guess it's a configuration setting in the proxy server that needs to be changed.

**Comment by kineticsquid** [comment]
@tivervac We discussed this internally and have decided that we will stay with our current limitation of 256M for an extension. Sorry!

**Comment by tivervac** [comment]
@kineticsquid Thank you for the transparency. I'm afraid we are forced to leave the platform as a result, though. We cannot have a marketplace that only lists out-of-date versions. I've created a [ticket](https://github.com/EclipseFdn/open-vsx.org/issues/2361) to request the removal of our app.
