### ISSUE TITLE
Searching for Publishers via Admin Console

### ISSUE THREAD

**Issue by SharonCorbett** [EclipseFdn/open-vsx.org#241]
The search criteria on Publishers seems to lock to GitHub ID only which is likely by design; however, greater flexibility in search criteria is expected so that rendered results serve back more information.  Example search on first name or last name, etc.

Not super urgent...just capturing.

**Comment by spoenemann** [comment]
The GitHub ID is the only reliable identifier for users. First / last name can be ambiguous. Since in the context of the publisher dashboard it is critical to apply actions on the correct user, we implemented the search as exact match on the login name (from GitHub). Usually you would just copy & paste that login name, e.g. from a GitHub issue or  email.

**Comment by brianking** [comment]
> The GitHub ID is the only reliable identifier for users. First / last name can be ambiguous. Since in the context of the publisher dashboard it is critical to apply actions on the correct user, we implemented the search as exact match on the login name (from GitHub). Usually you would just copy & paste that login name, e.g. from a GitHub issue or email.

Given this, I will close this for now.

@SharonCorbett Please reopen if you feel strongly it should be otherwise.
