### ISSUE TITLE
`mssql` in namespace `ms-mssql` is out of date

### ISSUE THREAD

**Issue by maxvolk** [EclipseFdn/open-vsx.org#2447]
The extension  https://open-vsx.org/extension/ms-mssql/mssql is out of date (last update in 2019).
It seems to be published by @open-vsx but is not listed in https://github.com/open-vsx/publish-extensions/blob/master/extensions.json . 
How can one see whether there is someone else managing this namespace and extension as an owner?
If there is none or the owner is unresponsive, should we add this extension to the `extensions.json`?

**Comment by kineticsquid** [comment]
@maxvolk Thanks for pointing this out. Yes, the extension was at one point published by the auto-publishing scripts of @open-vsx. But it looks like at some point it was removed. The `ms-mssql` namespace is owned by @chrisdias. Suggest you reach out to him. Since this extension is licensed under MIT (not all the MS extensions are) you can akways submit a PR to have it added (or re-added) to `extensions.json`.

**Comment by kineticsquid** [comment]
@maxvolk Any update on this?

**Comment by maxvolk** [comment]
@kineticsquid I have contacted @chrisdias but have not heard back regarding this.

**Comment by kineticsquid** [comment]
@maxvolk Go ahead ans submit a PR to have this auto-published

**Comment by kineticsquid** [comment]
@maxvolk I'm going to close this now. If you'd like this extension auto-published, you can it's made available under MIT, submit a PR as I mentioned above.
