### ISSUE TITLE
Claiming namespace pgourlain

### ISSUE THREAD

**Issue by pgourlain** [EclipseFdn/open-vsx.org#2517]
I'm the publisher of an extension for Visual Studio Code named 'Erlang' and my publisher name is "pgourlain" in the Visual Studio Market place 
- https://marketplace.visualstudio.com/items?itemName=pgourlain.erlang.
Some one ask me to publish on https://open-vsx.org/, and I would like to do with same publisher

kind regards.
Pierrick Gourlain

**Comment by pgourlain** [comment]
https://github.com/pgourlain/vscode_erlang/issues/283

**Comment by kineticsquid** [comment]
@pgourlain I've made you owner of the namespace. Note that @marcdumais-work is currently a contributor to this namespace.

**Comment by marcdumais-work** [comment]
> @pgourlain I've made you owner of the namespace. Note that @marcdumais-work is currently a contributor to this namespace.

Hi @kineticsquid,

I do not recall how I became a contributor to this namespace - it's possible that that published the extension in the early days of open-vsx. In any case I see no reason why I should remain as a contributor, specially since I have not signed the publisher agreement - could you remove me?

**Comment by kineticsquid** [comment]
@marcdumais-work Thanks for letting us know. I'll remove you.
