### ISSUE TITLE
Change default branch to use the production branch

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/open-vsx.org#391]
We expect PR to be submitted to the production branch but the default branch of this project is master.

By default, PR's are made against the default branch.  I would like to propose that we set the "production" branch as the new default branch to simply the process of submitting a PR.

I would also rename the master branch for the following reasons:

1. We are trying to avoid terms such as slave, master in our projects. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=568041
2. Master is misleading here since this branch is for publishing content on our staging server. I propose we called it "staging".

**Comment by chrisguindon** [comment]
I just noticed that this project doesn't have any branch protection. 

I just added branch protection rules to the production branch to avoid any force pushes.

**Comment by chrisguindon** [comment]
@mbarbero Do you agree that we should protect the `production` branch or would you prefer we protect `master`?

I am hoping to document the process.

**Comment by mbarbero** [comment]
Default branch is `master` because it is the branch where development happens. As such, it is and should stay the default branch (where development happens). Latest commit is always deployed to https://staging.open-vsx.org. Feel free to rename to `main` if you want as we don't have too many external contributors yet. You will have to fix the [Jenkinsfile](https://github.com/EclipseFdn/open-vsx.org/blob/master/Jenkinsfile#L77) though. 

The `production` branch is the branch being deployed to https://open-vsx.org. The idea is to have a separate branch which gets manually updated (with a merge commit) whenever the state on `master` is deemed prduction-ready. I would like to keep this process as it makes production more _stable_. It should not be the default branch. PR should still be submitted to the dev/master/main branch.

Which  [branch protection rules](https://docs.github.com/en/github/administering-a-repository/about-protected-branches#about-branch-protection-settings) do you want to setup on master/main and on production?

**Comment by chrisguindon** [comment]
Thanks @mbarbero,

I plan to make the following changes now:

- rename master branch with main branch (easier to do now than later)
- remove branch protection on the production branch and add it to the new "main" branch
- add a How to contribute section in the readme based off what we just discussed

**Comment by mbarbero** [comment]
> > Which branch protection rules do you want to setup on master/main and on production?
> 
> I want to disallow forces pushes on the main development branch. Forces pushes are allowed by default if you don't create a branch protection rule for it.

Sure, go ahead (as a matter of fact, it would be important for production as well)

**Comment by chrisguindon** [comment]
I prefer to have it on both! Let's do that!

**Comment by brianking** [comment]
Anything left to be done here?

**Comment by chrisguindon** [comment]
I think we are done!
