### ISSUE TITLE
VS Code api endpoint is not responsive

### ISSUE THREAD

**Issue by akosyakov** [EclipseFdn/open-vsx.org#660]
Searching and installing/uninstalling extensions from Gitpod VS Code is failing.

**Comment by mbarbero** [comment]
This is most probably caused by changes made to fix #633. 

@eclipsewebmaster mentioned in https://github.com/EclipseFdn/open-vsx.org/issues/633#issuecomment-912531486 that poor performance could appear when caching was less aggressive. See cpu usage of the deployment for the last 2 days:
![image](https://user-images.githubusercontent.com/452625/132466575-876892ba-727a-45b7-93ac-a6d9d0723657.png)

Meanwhile, in order to mitigate the issue until @eclipsewebmaster come back online, I've increased the number of replicas from 2 to 4. Let us know how it performs.

**Comment by akosyakov** [comment]
@mbarbero Should https://www.eclipsestatus.io/ be updated?

**Comment by mbarbero** [comment]
> @mbarbero Should https://www.eclipsestatus.io/ be updated?

Done.

**Comment by mbarbero** [comment]
The cpu load does not increase with the increased number of replicas
![image](https://user-images.githubusercontent.com/452625/132470545-9e73ae5a-6053-47c6-a623-21522da23528.png)
