### ISSUE TITLE
Extension published without a license

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/open-vsx.org#822]
Extensions require any license to be listed on open-vsx.org. The vsix tools has checks for this, however an extension seems to have evaded these checks and was published without a license.

https://open-vsx.org/extension/codesee/maps

**Comment by spoenemann** [comment]
It looks like the extension specifies `UNLICENSED` in its manifest (package.json). We once decided not to check the validity of specified licenses, even in such an obvious case. It's hard to verify, though, because the repository URL is not valid. Maybe it points to a private repository?

@shaneakr where does the extension come from? Does it really have no license? In that case we will have to delete it.

**Comment by brianking** [comment]
@shaneakr Any input here? We will have to remove the extension if you don't give any further guidance.

**Comment by kineticsquid** [comment]
@spoenemann I poked at this a bit. The Github repo links are no longer valid. Any reason why we should not remove this?

**Comment by spoenemann** [comment]
No, feel free to remove the extension.

**Comment by kineticsquid** [comment]
Thanks, removed all versions of the extension
